export const DISPLAY_ALERT= 'SHOW_ALERT'
export const CLEAR_ALRET = 'CLEAR_ALERT'

export const REGISER_UESR_BEGIN = 'REGISER_UESR_BEGIN'
export const REGISER_UESR_SUCCESS = 'REGISER_UESR_SUCCESS'
export const REGISER_UESR_ERROR = 'REGISER_UESR_ERROR'

export const LOGIN_UESR_BEGIN = 'LOGIN_UESR_BEGIN'
export const LOGIN_UESR_SUCCESS = 'LOGIN_UESR_SUCCESS'
export const LOGIN_UESR_ERROR = 'LOGIN_UESR_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'


export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'



